# MLX alignment tests against the torch-CPU fp32 reference cache
# (generated by gen_ref.py in a separate process — ref+mlx do not co-reside).
# Run: .venv/bin/python tests/align/mlx/gen_ref.py
#      .venv/bin/python -m pytest tests/align/mlx/test_align.py -q
import sys
from pathlib import Path

import numpy as np

import mlx.core as mx

mx.set_default_device(mx.cpu)  # alignment runs on CPU (deterministic, no Metal timeouts)

sys.path.insert(0, str(Path(__file__).parent))
from _ref import MLX, cos, max_abs, to_np

CACHE = Path(__file__).parent / "cache"
_mlx = None


def mlx():
    global _mlx
    if _mlx is None:
        from windextts_mlx.inference import WIndexTTSMLX

        _mlx = WIndexTTSMLX(weights_dir=MLX, dtype="fp32")
        # warmup + force eval: the first GPU kernel compile/lazy-eval can return
        # stale results on some Metal stacks; a small forced prefill stabilizes it.
        sm = mx.array([[0, 58839, 1]], dtype=mx.int32)
        w = _mlx.gpt._prefill(mx.zeros((1, 1, 1280), dtype=mx.float32), sm, mx.array([[1]], dtype=mx.int32))
        mx.eval(w)
        _ = None
    return _mlx


def load(name):
    return np.load(CACHE / f"{name}.npz")


def arr(z, key, dtype=None):
    a = z[key]
    return mx.array(a, dtype=dtype or mx.float32)


def check(name, a_t, a_m, cth=0.999, ath=None, label=""):
    c = cos(a_t, a_m)
    print(f"  {name}: cosine {c:.6f}" + (f" max_abs {max_abs(a_t, a_m):.2e}" if ath else ""))
    assert c > cth, f"{name} cosine {c:.6f} < {cth} {label}"
    if ath is not None:
        assert max_abs(a_t, a_m) < ath, f"{name} max_abs {max_abs(a_t, a_m):.2e}"


# ---------------- DSP frontends ----------------

def test_mel():
    z = load("mel")
    y = mlx()._mel()(arr(z, "audio"))
    check("mel", z["out"], y, cth=0.99999, ath=1e-3)


def test_featurizer():
    z = load("featurizer")
    f, m = mlx()._feat()(arr(z, "audio"), return_mask=True)
    check("featurizer", z["out"], f, cth=0.99999, ath=1e-3)
    assert (z["mask"] == np.asarray(m)).all(), "mask mismatch"


def test_fbank():
    z = load("fbank")
    f = mlx()._fbank()(arr(z, "audio"))
    check("fbank", z["out"], f, cth=0.99999, ath=1e-3)


def test_resample():
    z = load("resample")
    for out, tgt in (("out16", 16000), ("out22", 22050)):
        y = mlx()._resample(48000, tgt)(arr(z, "audio"))
        check(f"resample->{tgt}", z[out], y, cth=0.99999, ath=1e-4)


def test_normalizer():
    from windextts.frontend.normalizer import TextNormalizer

    n = TextNormalizer()
    for s in ("今天气温25度，我买了3.5斤苹果。", "Hello, this is test number 42!"):
        out = n.normalize(s)
        assert isinstance(out, str) and len(out) > 0
        print(f"  TN {s!r} -> {out!r}")


# ---------------- neural modules ----------------

def test_campplus():
    z = load("campplus")
    f = arr(z, "fbank")[None]  # [1,298,80] fbank features (already computed)
    y = mlx().campplus(f - f.mean(1, keepdims=True))
    check("campplus", z["out"], y, cth=0.9999)


def test_codec():
    z = load("codec_decode")
    y = mlx().codec.decode(arr(z, "codes", mx.int32))
    check("codec decode", z["out"], y, cth=0.9999)
    z = load("codec_quant")
    q = mlx().codec.quantize(arr(z, "z"))
    assert (z["idx"] == np.asarray(q[0])).all(), "quantize indices mismatch"
    check("codec quantize", z["out"], q[1], cth=0.9999)


def test_length_regulator():
    z = load("length_reg")
    y = mlx().length_regulator(arr(z, "x"), ylens=mx.array([200], dtype=mx.int32))[0]
    check("length_reg", z["out"], y, cth=0.9999, ath=1e-3)


def test_w2v_bert():
    z = load("w2v_bert")
    h = mlx().w2v_bert(arr(z, "feat"), arr(z, "mask", mx.int32), return_layer=17)
    check("w2v_bert", z["out"], h, cth=0.999)


def test_emo_conditioning():
    z = load("emo_cond")
    spk = arr(z, "spk")
    check("get_emovec", z["emovec"], mlx().gpt.get_emovec(spk), cth=0.999)
    check("merge_emovec", z["merged"], mlx().gpt.merge_emovec(spk, spk, alpha=0.5), cth=0.999)


def test_dit():
    z = load("dit")
    y = mlx().dit(arr(z, "x"), arr(z, "p"), mx.array([64, 64], dtype=mx.int32),
                  arr(z, "t"), arr(z, "s"), arr(z, "c"))
    check("dit", z["out"], y, cth=0.999, ath=1e-2)


def test_s2mel_inference():
    z = load("s2mel2")  # torch z snapshotted so the CFM solve is comparable
    y = mlx().s2mel.inference(arr(z, "spk"), arr(z, "s"), arr(z, "refmel"), arr(z, "style"),
                              n_timesteps=8, inference_cfg_rate=0.7, z=arr(z, "z"))
    check("s2mel", z["out"], y, cth=0.999, ath=1e-2)


def test_bigvgan():
    z = load("bigvgan")
    y = mlx().bigvgan(arr(z, "mel"))
    check("bigvgan", z["out"], y, cth=0.9999, ath=1e-3)


# ---------------- GPT-AR ----------------

def _gpt_case(z):
    conds = arr(z, "conds")
    tt = arr(z, "tt", mx.int32)
    lang = arr(z, "lang", mx.int32)
    return conds, tt, lang


def test_gpt_prefill():
    z = load("gpt_prefill")
    conds, tt, lang = _gpt_case(z)
    ids, emb, mask = mlx().gpt.prepare_gpt_inputs(conds, tt, lang)
    assert (z["ids"] == np.asarray(ids)).all(), "ids mismatch"
    assert (z["mask"] == np.asarray(mask)).all(), "mask mismatch"
    check("prefill emb", z["emb"], emb, cth=0.9999)
    _, _, _, lg = mlx().gpt._prefill(conds, tt, lang)
    check("prefill logits", z["logits"], lg, cth=0.999)


def test_gpt_greedy():
    z = load("gpt_greedy")
    conds, tt, lang = _gpt_case(z)
    codes = mlx().gpt.generate(conds, tt, lang, max_new_tokens=64, do_sample=False,
                               repetition_penalty=10.0,  # gen_ref uses 10.0 for greedy too
                               stop_token=mlx().cfg.gpt.stop_mel_token)
    nt, nm = z["codes"][0], to_np(codes)[0]
    same = (nt == nm).sum()
    print(f"  greedy codes: {same}/{len(nt)} identical")
    assert same / len(nt) >= 0.99, f"greedy match {same}/{len(nt)}"


def test_gpt_beam3():
    # do_sample=True: categorical RNG is framework-specific (torch.multinomial vs
    # mlx) so per-token equality is not reproducible; verify beam decode structure:
    # it runs, returns a sane-length sequence, and ends on the stop token.
    z = load("gpt_beam3")
    conds, tt, lang = _gpt_case(z)
    codes = mlx().gpt.generate(conds, tt, lang, max_new_tokens=64, do_sample=True,
                               top_k=30, top_p=0.8, temperature=0.8, repetition_penalty=10.0,
                               num_beams=3, stop_token=mlx().cfg.gpt.stop_mel_token)
    nm = to_np(codes)[0]
    assert 1 < len(nm) <= 64, f"unexpected beam3 length {len(nm)}"
    assert len(set(nm.tolist())) > 5, "beam3 output is degenerate (repeats)"
    print(f"  beam3 len {len(nm)} ok (RNG-dependent sampling: no per-token compare)")


# ---------------- end-to-end (test.wav) ----------------

def test_e2e():
    z = load("e2e")
    import soundfile as sf

    data, sr = sf.read("/Volumes/2T/WIndexTTS/test.wav", dtype="float32")
    data = data.mean(1) if data.ndim > 1 else data
    # match gen_ref ordering: resample FIRST, then truncate to 6s
    a16 = mlx()._resample(sr, 16000)(mx.array(data)[None])[:, : 16000 * 6]
    a22 = mlx()._resample(sr, 22050)(mx.array(data)[None])[:, : 22050 * 6]

    spk = mlx().extract_spk_cond(a16)
    style = mlx().extract_style(a16)
    refmel = mlx()._mel()(a22.astype(mx.float32))
    check("e2e spk_cond", z["spk_cond"], spk, cth=0.999)
    check("e2e style", z["style"], style, cth=0.999)
    check("e2e ref_mel", z["refmel"], refmel, cth=0.999)

    ev = mlx().build_emo_vec(style, spk)
    check("e2e emo_vec", z["emo_vec"], ev, cth=0.999)

    conds = mlx().gpt.build_conds_latent(style, ev)
    check("e2e conds", z["conds"], conds, cth=0.999)

    codes = mlx().gpt.generate(conds, arr(z, "tt", mx.int32), arr(z, "lang", mx.int32),
                               max_new_tokens=96, do_sample=False, stop_token=mlx().cfg.gpt.stop_mel_token)
    nt, nm = z["codes"][0], to_np(codes)[0]
    n = min(len(nt), len(nm))
    # tie-exempt comparison: a flip is only acceptable where the REFERENCE logits
    # top-2 gap is numerically tiny (cross-engine fp32 tie, not an impl bug);
    # AR cascade: a flip at k makes k+1..end incomparable (inputs differ), so the
    # free-run check passes iff all positions BEFORE the first flip match and the
    # first flip is a reference tie; the tail is then verified by FORCED decode.
    gaps = z["codes_gap"][:n] if "codes_gap" in z else np.zeros(n)
    tie = gaps < 0.05
    same = (nt[:n] == nm[:n])
    first = int(np.argmax(~same)) if not same.all() else None
    if first is None:
        print(f"  e2e greedy codes: {n}/{n} identical")
    else:
        assert same[:first].all(), f"code mismatch BEFORE first flip at {first}"
        print(f"  e2e greedy codes: {int(same.sum())}/{n} identical; first flip at "
              f"{first} (ref top-2 gap {gaps[first]:.4f}, {'tie-exempt' if tie[first] else 'REAL'})")
        assert tie[first], f"non-tie first flip at {first} (gap {gaps[first]:.4f})"
    # forced decode with the REFERENCE tokens: identical inputs => every non-tie
    # position must match exactly for the WHOLE sequence (the free-run tail is
    # driven by divergent inputs, so it cannot be compared position-by-position).
    S, am, kvs, cl = mlx().gpt._prefill(conds, arr(z, "tt", mx.int32), arr(z, "lang", mx.int32))
    fd = [int(np.asarray(cl)[0, -1].argmax())]
    for step in range(n - 1):
        am, kvs, cl = mlx().gpt._eager_step(mx.array([[int(nt[step])]], dtype=mx.int32), step, am, kvs, mx.float32)
        fd.append(int(np.asarray(cl)[0].argmax()))
    fd = np.array(fd)
    fd_bad = [i for i in range(n) if fd[i] != nt[i] and not tie[i]]
    print(f"  e2e forced-decode: {int((fd == nt).sum())}/{n} identical "
          f"(non-tie mismatches {fd_bad})")
    assert not fd_bad, f"forced-decode non-tie mismatch at {fd_bad}"

    # decode-chain alignment must use the REFERENCE codes (generation ties may
    # diverge, but codec->mel->vocoder parity is judged on identical input)
    s = mlx().codec.decode(arr(z, "codes", mx.int32))
    check("e2e s_infer", z["s"], s, cth=0.999)
    mel = mlx().s2mel.inference(spk, s, refmel, style, n_timesteps=8, inference_cfg_rate=0.7,
                                z=arr(z, "z") if "z" in z else None)
    check("e2e mel", z["mel"], mel, cth=0.999)
    aud = np.asarray(mx.clip(mlx().bigvgan(mel), -1.0, 1.0)[0, 0])
    check("e2e audio", z["audio"], aud, cth=0.99, label="audio")
